# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aeb40140a30e852201016309b8922ff35ab48be0ffea306f7b17314aee19f61b238b3ce2644a759e45f6a7b5a6db101f20b7889943881c9c08eee5fd87140f21

test:
  secret_key_base: e3a24daabbdbda76dc76df6906f4ab28a909c134ba718fde93af16ebdc1e3af69bd2f4f458b95e321065871f7bab10f4aa3cc9179a233bdbbe30d9ba891495a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
